name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache trhe correctly
      # and run all Cypress test
      - name: Cypress run
        uses: cypress-io/github-actions@v6